[package]
name = "arandu_backend_cranelift"
version = "0.1.7"
edition = "2024"
license.workspace = true
authors.workspace = true

[dependencies]
arandu_base = { path = "../arandu_base" }
arandu_codegen = { path = "../arandu_codegen" }
arandu_runtime = { path = "../arandu_runtime" }
arandu_semantics = { path = "../arandu_semantics" }
cranelift-codegen = "0.134.3"
cranelift-frontend = "0.134.3"
cranelift-jit = "0.134.3"
cranelift-module = "0.134.3"
cranelift-native = "0.134.3"
cranelift-object = "0.134.3"
target-lexicon = "0.13.5"
blake3 = { workspace = true }
rustc-hash = { workspace = true }
tracing.workspace = true

[dev-dependencies]
arandu_parser = { path = "../arandu_parser" }
