//! Shared canonical source graph for stdlib integration tests.
#![allow(clippy::expect_used)]

pub const STDLIB_MODULES: &[(&str, &str)] = &[
    (
        "stdlib/alloc/allocator_api.aru",
        include_str!("../../../../stdlib/alloc/allocator_api.aru"),
    ),
    (
        "stdlib/alloc/arena.aru",
        include_str!("../../../../stdlib/alloc/arena.aru"),
    ),
    (
        "stdlib/alloc/bitset.aru",
        include_str!("../../../../stdlib/alloc/bitset.aru"),
    ),
    (
        "stdlib/alloc/gen_arena.aru",
        include_str!("../../../../stdlib/alloc/gen_arena.aru"),
    ),
    (
        "stdlib/alloc/hash_map.aru",
        include_str!("../../../../stdlib/alloc/hash_map.aru"),
    ),
    (
        "stdlib/alloc/smallvec.aru",
        include_str!("../../../../stdlib/alloc/smallvec.aru"),
    ),
    (
        "stdlib/alloc/string.aru",
        include_str!("../../../../stdlib/alloc/string.aru"),
    ),
    (
        "stdlib/alloc/vec.aru",
        include_str!("../../../../stdlib/alloc/vec.aru"),
    ),
    (
        "stdlib/core/ascii.aru",
        include_str!("../../../../stdlib/core/ascii.aru"),
    ),
    (
        "stdlib/core/atomic.aru",
        include_str!("../../../../stdlib/core/atomic.aru"),
    ),
    (
        "stdlib/core/cell.aru",
        include_str!("../../../../stdlib/core/cell.aru"),
    ),
    (
        "stdlib/core/char.aru",
        include_str!("../../../../stdlib/core/char.aru"),
    ),
    (
        "stdlib/core/cmp.aru",
        include_str!("../../../../stdlib/core/cmp.aru"),
    ),
    (
        "stdlib/core/fixed.aru",
        include_str!("../../../../stdlib/core/fixed.aru"),
    ),
    (
        "stdlib/core/fmt.aru",
        include_str!("../../../../stdlib/core/fmt.aru"),
    ),
    (
        "stdlib/core/future.aru",
        include_str!("../../../../stdlib/core/future.aru"),
    ),
    (
        "stdlib/core/hash.aru",
        include_str!("../../../../stdlib/core/hash.aru"),
    ),
    (
        "stdlib/core/intrinsics.aru",
        include_str!("../../../../stdlib/core/intrinsics.aru"),
    ),
    (
        "stdlib/core/io.aru",
        include_str!("../../../../stdlib/core/io.aru"),
    ),
    (
        "stdlib/core/iter.aru",
        include_str!("../../../../stdlib/core/iter.aru"),
    ),
    (
        "stdlib/core/marker.aru",
        include_str!("../../../../stdlib/core/marker.aru"),
    ),
    (
        "stdlib/core/mem.aru",
        include_str!("../../../../stdlib/core/mem.aru"),
    ),
    (
        "stdlib/core/num.aru",
        include_str!("../../../../stdlib/core/num.aru"),
    ),
    (
        "stdlib/core/option.aru",
        include_str!("../../../../stdlib/core/option.aru"),
    ),
    (
        "stdlib/core/pointer.aru",
        include_str!("../../../../stdlib/core/pointer.aru"),
    ),
    (
        "stdlib/core/prelude.aru",
        include_str!("../../../../stdlib/core/prelude.aru"),
    ),
    (
        "stdlib/core/result.aru",
        include_str!("../../../../stdlib/core/result.aru"),
    ),
    (
        "stdlib/core/slice.aru",
        include_str!("../../../../stdlib/core/slice.aru"),
    ),
    (
        "stdlib/core/str.aru",
        include_str!("../../../../stdlib/core/str.aru"),
    ),
    (
        "stdlib/math/linalg.aru",
        include_str!("../../../../stdlib/math/linalg.aru"),
    ),
    (
        "stdlib/math/matrix.aru",
        include_str!("../../../../stdlib/math/matrix.aru"),
    ),
    (
        "stdlib/math/view.aru",
        include_str!("../../../../stdlib/math/view.aru"),
    ),
    (
        "stdlib/std/env.aru",
        include_str!("../../../../stdlib/std/env.aru"),
    ),
    (
        "stdlib/std/fs.aru",
        include_str!("../../../../stdlib/std/fs.aru"),
    ),
    (
        "stdlib/std/io.aru",
        include_str!("../../../../stdlib/std/io.aru"),
    ),
    (
        "stdlib/std/net.aru",
        include_str!("../../../../stdlib/std/net.aru"),
    ),
    (
        "stdlib/std/parallel.aru",
        include_str!("../../../../stdlib/std/parallel.aru"),
    ),
    (
        "stdlib/std/path.aru",
        include_str!("../../../../stdlib/std/path.aru"),
    ),
    (
        "stdlib/std/process.aru",
        include_str!("../../../../stdlib/std/process.aru"),
    ),
    (
        "stdlib/std/runtime/channel.aru",
        include_str!("../../../../stdlib/std/runtime/channel.aru"),
    ),
    (
        "stdlib/std/runtime/executor.aru",
        include_str!("../../../../stdlib/std/runtime/executor.aru"),
    ),
    (
        "stdlib/std/runtime/mutex.aru",
        include_str!("../../../../stdlib/std/runtime/mutex.aru"),
    ),
    (
        "stdlib/std/runtime/reactor.aru",
        include_str!("../../../../stdlib/std/runtime/reactor.aru"),
    ),
    (
        "stdlib/std/runtime/supervisor.aru",
        include_str!("../../../../stdlib/std/runtime/supervisor.aru"),
    ),
    (
        "stdlib/std/runtime/waker.aru",
        include_str!("../../../../stdlib/std/runtime/waker.aru"),
    ),
    (
        "stdlib/std/testing.aru",
        include_str!("../../../../stdlib/std/testing.aru"),
    ),
    (
        "stdlib/std/time.aru",
        include_str!("../../../../stdlib/std/time.aru"),
    ),
];
