[package]
name = "arandu_lexer"
version = "0.1.7"
edition = "2024"
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
arandu_base = { path = "../arandu_base" }
unicode-ident = "1.0"

[dev-dependencies]
arandu_test_support = { path = "../arandu_test_support" }
