[package]
name = "arandu_cli"
version = "0.1.7"
edition = "2024"
license.workspace = true
authors.workspace = true

[features]
default = ["self-profile"]
self-profile = ["arandu_base/self-profile"]

[lints]
workspace = true

[lib]
name = "arandu_package"
path = "src/lib.rs"

[dependencies]
arandu_lexer = { path = "../arandu_lexer" }
arandu_parser = { path = "../arandu_parser" }
arandu_semantics = { path = "../arandu_semantics" }
arandu_backend_cranelift = { path = "../arandu_backend_cranelift" }
arandu_backend_c = { path = "../arandu_backend_c" }
arandu_backend_wasm = { path = "../arandu_backend_wasm" }
arandu_codegen = { path = "../arandu_codegen" }
arandu_runtime = { path = "../arandu_runtime" }
arandu_query = { path = "../arandu_query" }
arandu_fmt = { path = "../arandu_fmt" }
arandu_doc = { path = "../arandu_doc" }

arandu_middle = { path = "../arandu_middle" }
arandu_base = { path = "../arandu_base" }
tracing.workspace = true
blake3 = { workspace = true }
sha2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rayon = "1.12.0"
miette = { workspace = true }
petgraph = { workspace = true }
notify = "8.2.0"
notify-debouncer-full = "0.7.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2.189"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.60.2", features = [
    "Win32_Storage_FileSystem",
    "Win32_System_Pipes",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_JobObjects",
    "Win32_System_Console",
] }
