[package]
name = "arandu_backend_wasm"
version = "0.1.7"
edition = "2024"
license.workspace = true
authors.workspace = true

[dependencies]
arandu_base = { path = "../arandu_base" }
arandu_codegen = { path = "../arandu_codegen" }
arandu_middle = { path = "../arandu_middle" }
arandu_semantics = { path = "../arandu_semantics" }
wasm-encoder = { workspace = true }
rustc-hash = { workspace = true }
smallvec = { workspace = true }
smol_str = { workspace = true }
wit-component = { workspace = true }
wit-parser = { workspace = true }

[dev-dependencies]
arandu_query = { path = "../arandu_query" }
arandu_semantics = { path = "../arandu_semantics" }
wasmparser = { workspace = true }
wasmtime = "47"


[lints]
workspace = true
